storage: ../tmp/local-registry/storage

web:
  title: Continuum (local Verdaccio)

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
  '@*/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    unpublish: $all

middlewares:
  audit:
    enabled: true

server:
  keepAliveTimeout: 60

log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true
